language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 7.0
      env: setup=lowest
    - php: 7.0
      env: setup=stable
    - php: 7.1
      env: setup=lowest
    - php: 7.1
      env: setup=stable

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

before_script: mkdir -p build/logs

script: vendor/bin/phpunit

after_script: vendor/bin/coveralls -v -n
